### ISSUE TITLE
Add travis.yml

### ISSUE THREAD

**Issue by sks444** [CodeVINCI/good-food-project#6]
We should have some CI working on this repo, which would make reviewing easy, and any problem in the project will be directly reported, if the CI fail. And no PR should be merged until the CI is passed.

**Comment by RaiVaibhav** [comment]
Appreciate your work but currently `linting` is not problem but problem is to `somehow` check the work on the `PR` is reflecting on `site` or not, it will give a serious help.

**Comment by CodeVINCI** [comment]
let's keep linting too from the start of the project.

**Comment by RaiVaibhav** [comment]
yes `travis` and `.coafile` will take care of that.
