### ISSUE TITLE
Switch to postgresql

### ISSUE THREAD

**Issue by sks444** [CodeVINCI/good-food-project#8]
We are currently using django's inbuilt database `sqlite3` we should switch to `postgresql` for a good database experience.

**Comment by CodeVINCI** [comment]
Assign me if you are made a collaborator now

On Apr 18, 2018 10:04 PM, "Shrikrishna Singh" <notifications@github.com>
wrote:
>
> We are currently using django's inbuilt database sqlite3 we should switch
to postgresql for a good database experience.

**Comment by sks444** [comment]
@CodeVINCI; please don't push the env variables; see https://simpleisbetterthancomplex.com/2015/11/26/package-of-the-week-python-decouple.html on how to handle those.
we will need `.env` file.
Also, document the names of env var in README.md setup, when you will push the changes.
